# fly.toml file generated for reactivities-mario on 2022-11-29T17:00:34-01:00

app = "reactivities-mario"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "mariotravanca/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dowkcyhbw"
  Cloudinary__ApiKey="122163524312146"
  Facebook__AppId="523269269794553"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
